In [4]:
import numpy as np
import pandas as pd
matriz = np.array([[1,2,3],[4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

# !pip install numpy"

In [8]:
type(matriz)

numpy.ndarray

In [32]:
# Multiplicando arrays
array2 = np.random.randint(0,30,size=(2, 3))
print("array1{}".format(array1))
print("array2{}".format(array2))
result = array1+array2
result

array1[[23 22  1]
 [12  1  7]]
array2[[20  9  0]
 [10 17 22]]


array([[43, 31,  1],
       [22, 18, 29]])

In [34]:
# mutiplicando array por escalar
array = np.array([1,2,3])
multi_by_escalar = 2*array
multi_by_escalar

array([2, 4, 6])

In [39]:
# matriz identidade
i = np.eye(4)


In [58]:
# resize array 1D to 3D
array_1d = np.array([x for x in range(27)])
array_1d
array_3d = array_1d.reshape(3,3,3)     
array_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])